pretrained_base_model_path: "./checkpoints/sd-image-variations-diffusers"
pretrained_vae_path: "stabilityai/sd-vae-ft-mse"
image_encoder_path: "./checkpoints/image_encoder"
denoising_unet_path: "./checkpoints/denoising_unet/denoising_unet.pth"
reference_unet_path: "./checkpoints/reference_unet/reference_unet.pth"
pose_guider_pretrain: True
pose_guider_path: "./checkpoints/pose_guider/pose_guider.pth"
#motion_module_path: "./pretrained_weights/motion_module.pth"

inference_config: "./configs/inference/inference_v2.yaml"
weight_dtype: 'fp32'

data:
  train_bs: 1
  train_width: 256 
  train_height: 256 
  train_seg_width: 256
  train_seg_height: 256
  real_images_path: "/media/dataset2/CityScape/leftImg8bit/train"
  seg_images_path: "/media/dataset2/CityScape/gtFine/train" #"/media/dataset1/init_cond/sunny"
  mode: "retrieve_dino"

test_cases:
  "./test_imgs/reference/leverkusen_000013_000019.png":
    - "./test_imgs/seg_map/frankfurt_000000_001751.png"
    - "./test_imgs/seg_map/frankfurt_000000_003025.png"
    - "./test_imgs/seg_map/lindau_000014_000019.png"